---
apiVersion: skupper.io/v2alpha1
kind: Site
metadata:
  name: c01
spec:
  linkAccess: default
---
apiVersion: skupper.io/v2alpha1
kind: Connector
metadata:
  name: hazelcast
spec:
  exposePodsByName: true
  port: 5701
  routingKey: hazelcast
  selector: app=hazelcast
  type: tcp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hazelcast-config
data:
  hazelcast.yaml: |-
    hazelcast:
      network:
        public-address: ${advertiseName}
        join:
          kubernetes:
            enabled: true
            service-dns: ${serviceName}
---
apiVersion: v1
kind: Service
metadata:
  name: hazelcast
spec:
  selector:
    app: hazelcast
  clusterIP: None
  ports:
  - name: hazelcast
    port: 5701
    targetPort: 5701
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hazelcast
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hazelcast
  serviceName: hazelcast
  template:
    metadata:
      labels:
        app: hazelcast
    spec:
      containers:
      - name: hazelcast
        image: "hazelcast/hazelcast:5.5.0"
        ports:
        - containerPort: 5701
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: JAVA_OPTS
          value: "-Dhazelcast.config=/data/hazelcast/hazelcast.yaml -DserviceName=hazelcast -DadvertiseName=$(POD_NAME)"
        volumeMounts:
        - name: hazelcast-config-volume
          mountPath: /data/hazelcast
      dnsConfig:
        searches:
          - hazelcast.MY_NAMESPACE.svc.cluster.local
      volumes:
      - name: hazelcast-config-volume
        configMap:
          name: hazelcast-config
