---
apiVersion: skupper.io/v2alpha1
kind: Connector
metadata:
  name: hcext
spec:
  exposePodsByName: true
  port: 5701
  routingKey: hazelcast-ext
  selector: app=hcext
  type: tcp
---
apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: hz-client-members
spec:
  exposePodsByName: true
  host: hz-client-members
  routingKey: hazelcast-ext
  port: 5701
  type: tcp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hcext-config
data:
  hazelcast.yaml: |-
    hazelcast:
      network:
        public-address: ${advertiseName}
        join:
          kubernetes:
            enabled: true
            service-dns: ${serviceName}
---
apiVersion: v1
kind: Service
metadata:
  name: hcext
spec:
  selector:
    app: hcext
  clusterIP: None
  ports:
  - name: hazelcast
    port: 5701
    targetPort: 5701
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcext
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hcext
  template:
    metadata:
      labels:
        app: hcext
    spec:
      containers:
      - name: hazelcast
        image: "hazelcast/hazelcast:5.5.0"
        ports:
        - containerPort: 5701
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: JAVA_OPTS
          value: "-Dhazelcast.config=/data/hazelcast/hazelcast.yaml -DserviceName=hazelcast -DadvertiseName=$(POD_NAME)"
        volumeMounts:
        - name: hazelcast-config-volume
          mountPath: /data/hazelcast
      volumes:
      - name: hazelcast-config-volume
        configMap:
          name: hcext-config
