---
apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: hz-cluster-members
spec:
  exposePodsByName: true
  host: hz-cluster-members
  routingKey: hazelcast
  port: 5701
  type: tcp
---
apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: hz-client-members
spec:
  exposePodsByName: true
  host: hz-client-members
  routingKey: hazelcast-ext
  port: 5701
  type: tcp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hazelcast-mancenter-config
data:
  hazelcast-client.yaml: |-
    hazelcast-client:
      network:
        kubernetes:
          enabled: true
          service-dns: ${serviceName}
---
apiVersion: v1
kind: Service
metadata:
  name: hazelcast-mancenter
  labels:
    app.kubernetes.io/name: hazelcast-mancenter
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: hazelcast-mancenter
    role: mancenter
  ports:
  - protocol: TCP
    port: 8080
    targetPort: mancenter
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast-mancenter
  labels:
    app.kubernetes.io/name: hazelcast-mancenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hazelcast-mancenter
      role: mancenter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hazelcast-mancenter
        role: mancenter
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      containers:
      - name: hazelcast-mancenter
        image: "hazelcast/management-center:5.5.2"
        imagePullPolicy: "IfNotPresent"
        ports:
        - name: mancenter
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: config
          mountPath: /config
        - name: mancenter-storage
          mountPath: /data
        env:
        - name: MC_INIT_CMD
          value: "./bin/hz-mc conf cluster add --lenient=true -H /data -cc /config/hazelcast-client.yaml;"   
        - name: JAVA_OPTS
          value: "-Dhazelcast.mc.healthCheck.enable=true -DserviceName=hazelcast -Dhazelcast.mc.tls.enabled=false"
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          runAsGroup: 65534
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: config
        configMap:
           name: hazelcast-mancenter-config
      - name: mancenter-storage
        emptyDir:
          sizeLimit: 4G
